#!/usr/bin/env python3
import re
import sys
import argparse
from logging import Logger, basicConfig, getLogger
from os import getenv, environ, pathsep, fspath
from pathlib import Path, PurePath
from typing import List, Set, Optional
from subprocess import call

if __name__ == "__main__":
    basicConfig(
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
        level=getenv('LOG_LEVEL', 'INFO'),
    )
    parser = argparse.ArgumentParser(description='Expander')
    parser.add_argument('source', help='Source File')
    parser.add_argument('-c', '--console',
                        action='store_true', help='Print to Console')
    parser.add_argument('-ac', '--atcoder', action='store_true', help='Expand at atcoder_acc')
    parser.add_argument('-cf', '--codeforces', action='store_true', help='Expand at codeforces_new')
    parser.add_argument('-yk', '--yukicoder', action='store_true', help='Expand at yukicoder_oj')
    opts = parser.parse_args()

    if opts.atcoder:
        expande_ac_command = ["python3", "../../../otera-cp-library/expander.py", "--lib", "../../../otera-cp-library", opts.source]
        call(expande_ac_command)
    if opts.codeforces:
        expande_cf_command = ["python3", "../../../otera-cp-library/expander.py", "--lib", "../../../otera-cp-library", opts.source, "-ac"]
        call(expande_cf_command)
    if opts.yukicoder:
        expande_yk_command = ["python3", "../../otera-cp-library/expander.py", "--lib", "../../otera-cp-library", opts.source]
        call(expande_yk_command)